// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {Big} x
 * @param {Big} y
 * @returns {Promise.<void>}
 */
export async function GestureAt(x, y) {
	// BEGIN USER CODE
	if (window.__clippyAgent) {
		return new Promise((succes) => {
			window.__clippyAgent.gestureAt(x, y, succes);
		});
	}
	// END USER CODE
}
